-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Changing the columns in a view requires dropping and re-creating the view.
-- This may fail if other objects are dependent upon this view,
-- or may cause procedural functions to fail if they are not modified to
-- take account of the changes.
DROP VIEW public.job_board;
CREATE OR REPLACE VIEW public.job_board
    AS
     WITH jobs AS (
         SELECT job.job_id,
            job.title,
            job.reward,
            job.job_description_url,
            job.created_at,
            job.updated_at,
            company.company_name
           FROM job
             JOIN company USING (company_id)
        ), locations AS (
         SELECT job.job_id,
            array_agg(job_location.location_name ORDER BY job_location.location_name) AS locations
           FROM job
             LEFT JOIN job_location USING (job_id)
          GROUP BY job.job_id
        )
 SELECT jobs.job_id,
    jobs.title,
    jobs.reward,
    jobs.job_description_url,
    jobs.created_at,
    jobs.updated_at,
    jobs.company_name,
    locations.locations
   FROM jobs
     LEFT JOIN locations USING (job_id)
  ORDER BY jobs.reward DESC;
GRANT ALL ON TABLE public.job_board TO authenticated;
GRANT ALL ON TABLE public.job_board TO postgres;
GRANT ALL ON TABLE public.job_board TO anon;
GRANT ALL ON TABLE public.job_board TO service_role;
