-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

alter publication supabase_realtime add table profile;
alter publication supabase_realtime add table company;
alter publication supabase_realtime add table job;
alter publication supabase_realtime add table job_location;
