-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP POLICY IF EXISTS "Referrers can insert their own referral." ON public.referral;

CREATE POLICY "Referrers can insert their own referral but not themselves"
    ON public.referral
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (((auth.uid() = referrer_id) AND (auth.email() <> candidate_email)));

